version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: library_postgres
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: library_redis
    ports:
      - "1453:6379"
    networks:
      - app-network

  app:
    build: .
    container_name: library_app
    depends_on:
      - postgres
      - redis
    ports:
      - "8070:8070"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/library_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET_ENV: a2V5LWZvci1naXRodWItaXNzdWUtZGVtbzEyMzQ1Njc4OQ==
    networks:
      - app-network

volumes:
  pg_data:

networks:
  app-network:
