server:
  port: 8070

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: admin
      password: zkxnvzlknvakjnvzjxbvzhbxvxjz12412412_-
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 1453
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.getir.library_management: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/library-system.log

