server:
  port: 8070

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/libraryDb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: admin
      password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
