server:
  port: 8070

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/library_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: a2V5LWZvci1naXRodWItaXNzdWUtZGVtbzEyMzQ1Njc4OQ==

logging:
  level:
    root: WARN
    org.springframework.security: ERROR
    com.getir.library_management: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/library-system.log
